### ISSUE TITLE
   Rendering SLS "base:bind.config" failed: Conflicting ID "zones-"

### ISSUE THREAD

**Issue by masterkorp** [saltstack-formulas/bind-formula#12] opened 2014-06-12 11:15 UTC
Hello,

I am trying kitchen-salt to play with this formula.
I am loding the pillar.example file to pillar data, running the bind.config state.

```
       Transfering files to <default-ubuntu-1404-i386>
[INFO    ] Using cached minion ID from /etc/salt/minion_id: default-ubuntu-1404-i386.vagrantup.com       
[INFO    ] Loading fresh modules for state activity       
[INFO    ] Creating module dir '/var/cache/salt/minion/extmods/modules'       
[INFO    ] Syncing modules for environment 'base'       
[INFO    ] Loading cache from salt://_modules, for base)       
[INFO    ] Caching directory '_modules/' for environment 'base'       
[INFO    ] Creating module dir '/var/cache/salt/minion/extmods/states'       
[INFO    ] Syncing states for environment 'base'       
[INFO    ] Loading cache from salt://_states, for base)       
       [INFO    ] Caching directory '_states/' for environment 'base'
[INFO    ] Creating module dir '/var/cache/salt/minion/extmods/grains'       
[INFO    ] Syncing grains for environment 'base'       
[INFO    ] Loading cache from salt://_grains, for base)       
[INFO    ] Caching directory '_grains/' for environment 'base'       
[INFO    ] Creating module dir '/var/cache/salt/minion/extmods/renderers'       
[INFO    ] Syncing renderers for environment 'base'       
[INFO    ] Loading cache from salt://_renderers, for base)       
[INFO    ] Caching directory '_renderers/' for environment 'base'       
[INFO    ] Creating module dir '/var/cache/salt/minion/extmods/returners'       
[INFO    ] Syncing returners for environment 'base'       
       [INFO    ] Loading cache from salt://_returners, for base)
[INFO    ] Caching directory '_returners/' for environment 'base'       
[INFO    ] Creating module dir '/var/cache/salt/minion/extmods/outputters'       
[INFO    ] Syncing outputters for environment 'base'       
[INFO    ] Loading cache from salt://_outputters, for base)       
[INFO    ] Caching directory '_outputters/' for environment 'base'       
[INFO    ] Loading fresh modules for state activity       
[CRITICAL] Rendering SLS "base:bind.config" failed: Conflicting ID "zones-"       
local:       
    Data failed to compile:       
       ----------
           Rendering SLS "base:bind.config" failed: Conflicting ID "zones-"
salt-call exit code: 0       
salt-call output grep exit code 1       
       Finished converging <default-ubuntu-1404-i386> (6m12.68s).
```

Isn't pillar example data suposed to work out of the box ?

**Comment by cosu** [comment] 2015-03-06 10:27
I think the problem was that pillar data for available_zones outside of the bind tree. And the zone- section was iterating over an empty data structure.  I just hit this same bug in  my config a minute ago and after I moved the available_zones under the bind key it went away.

**Comment by aanriot** [comment] 2018-06-05 13:25
Thanks @cosu . As the issue is old, I will now close it.

**Closed by aanriot** 2018-06-05 13:25 UTC
