### ISSUE TITLE
documentation: in the pillar example, dash before single item

### ISSUE THREAD

**Issue by mjinks** [saltstack-formulas/bind-formula#34] opened 2015-08-13 01:00 UTC
Currently:

  bind:
    lookup:
      pkgs:
        - bind
      service: named

Shouldn't that be:

  bind:
    lookup:
      pkgs: bind
      service: named

...?

**Comment by tedski** [comment] 2016-04-17 15:03
In [map.jinja](https://github.com/tedski/bind-formula/blob/master/bind/map.jinja#L3), you'll note that `pkgs` takes a list of packages to install.  The `pillar.example` is accurate for overriding packages.  

For example, on Debian Jessie, `dnssec-utils` is not available, so one must edit their pillar example to suit:
```
bind:
  lookup:
    pkgs:
      - bind9
      - bind9utils
```

Recommend closing as not a bug, @gravyboat

**Comment by gravyboat** [comment] 2016-04-17 18:20
Yeah I'll close this, it's a pretty old issue.

**Closed by gravyboat** 2016-04-17 18:20 UTC
